---
title: "Maurício Vancine"
author: Maurício Vancine
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: true
    css: resume.css
---

Aside
================================================================================

Contact {#contact}
--------------------------------------------------------------------------------
- `r icons::fontawesome("link")` [mauriciovancine.github.io](https://mauriciovancine.github.io/)
- `r icons::fontawesome("envelope", style = "solid")` mauricio.vancine@gmail.com
- `r icons::fontawesome("twitter")` [mauriciovancine](https://twitter.com/mauriciovancine)
- `r icons::fontawesome("github")` [github/mauriciovancine](https://github.com/mauriciovancine)
- `r icons::academicons("orcid")` [0000-0001-9650-7575](https://orcid.org/0000-0001-9650-7575)
- `r icons::academicons("lattes")` [9761288418931193](http://lattes.cnpq.br/9761288418931193)

Themes {#themes}
--------------------------------------------------------------------------------
- `r icons::fontawesome("globe")` `Spatial Ecology`
- `r icons::fontawesome("globe-americas")` `Landscape Ecology`
- `r icons::fontawesome("chart-bar")` `Ecological Modeling`
- `r icons::fontawesome("layer-group")` `Geoprocessing`
- `r icons::fontawesome("frog")` `Amphibian Ecology`

Skills {#skills}
--------------------------------------------------------------------------------
- `r icons::fontawesome("r-project")` [`R`](https://www.r-project.org/)
- `r icons::fontawesome("laptop-code")` [`tidyverse`](https://www.tidyverse.org/)
- `r icons::fontawesome("markdown")` [`markdown`](https://daringfireball.net/projects/markdown/)
- `r icons::fontawesome("code-branch")` [`git (básico)`](https://git-scm.com/)
- `r icons::fontawesome("python")` [`python (básico)`](https://www.python.org/)
- `r icons::fontawesome("terminal")` [`bash (básico)`](https://www.gnu.org/software/bash/)
- `r icons::fontawesome("quora")` [`QGIS`](https://qgis.org/en/site/)
- `r icons::fontawesome("seedling")` [`GRASS GIS`](https://grass.osgeo.org/)
- `r icons::fontawesome("linux")` [`GNU/Linux`](https://www.gnu.org/gnu/linux-and-gnu.html)

Languages {#languages}
--------------------------------------------------------------------------------
- Portuguese (Native speaker)
- English (Intermediate)
- Spanish (Basic)

<i class='fas fa-file-pdf'></i> [Download PDF](https://mauriciovancine.github.io/cv/cv-mauricio-vancine-en-academic-complete.pdf)
<br>
<i class='fas fa-download'></i> [Short version](https://mauriciovancine.github.io/cv/cv-mauricio-vancine-en-academic-short.html)

Disclaimer {#disclaimer}
------------------------------------
CV by [**pagedown**](https://github.com/rstudio/pagedown) R package.  
Code available on `r icons::fontawesome("github")` [GitHub](https://github.com/mauriciovancine/cv).  
Last updated on `r Sys.Date()`.

Main
================================================================================

Maurício Vancine {#title}
--------------------------------------------------------------------------------

### Doctoral Student in Ecology, Evolution and Biodiversity

I am a Spatial Ecologist and PhD student at Unesp Rio Claro, Brazil. I have experience in landscape ecology, habitat loss and fragmentation, amphibian ecology, species distribution modeling, and analysis of ecological and spatial data.

Education {data-icon=graduation-cap}
--------------------------------------------------------------------------------

### São Paulo State University (UNESP)

[Doctoral Student in Ecology, Evolution and Biodiversity](https://ib.rc.unesp.br/#!/pos-graduacao/secao-tecnica-de-pos/programas/ecologia-e-biodiversidade/apresentacao-novo/)

Rio Claro, SP, Brazil

2020 - Present

**Thesis**: Landscape structure as a predictor of taxonomic and functional diversity of amphibians in the Atlantic Forest
**Advisor**: Prof. Milton Cezar Ribeiro

### São Paulo State University (UNESP)

[Master in Zoology](https://ib.rc.unesp.br/#!/pos-graduacao/secao-tecnica-de-pos/programas/zoologia/)

Rio Claro, SP, Brazil

2016 - 2018

**Thesis**: Diversity, distribution and effect of climate change on Atlantic Forest amphibian communities ([UNESP Libraries](https://repositorio.unesp.br/handle/11449/154993))  
**Advisor**: Prof. Célio Fernando Baptista Haddad

### São Paulo State University (UNESP)

[Bachelor in Ecology](https://ib.rc.unesp.br/#!/graduacao/cursos-conselho-de-curso/ecologia/)

Rio Claro, SP, Brazil

2011 - 2014

**Thesis**: Effect of fragmentation on the persistence of anuran amphibians (Amphibia: Anura) within the Atlantic Forest ([UNESP Libraries](https://repositorio.unesp.br/handle/11449/138991))  
**Advisor**: Prof. Milton Cezar Ribeiro

Complementary Education {data-icon=chalkboard}
--------------------------------------------------------------------------------

### Joint Species Distribution Modelling with HMSC

University of Jyväskylä (Online)

Jyväskylä, Finlândia

2022

::: concise
- 45 h 
- [course](https://www.helsinki.fi/en/researchgroups/statistical-ecology/software/hmsc)
:::

### Data Science Journey

Ômega Data Science (Online)

Curitiba, Paraná

2022

::: concise
- 330 h 
- [course](https://omegadatascience.com.br/)
:::

### Hierarchical Modelling of Species Communities with the R-package Hmsc

University of Helsinki (Online)

Helsinki, Finland

2020

::: concise
- 25 h 
- [course](https://www.helsinki.fi/en/researchgroups/statistical-ecology/hmsc)
:::

### School on Community Ecology: from patterns to principles

São Paulo State University (UNESP)

São Paulo, SP, Brazil

2020

::: concise
- 60 h 
- [course](https://www.ictp-saifr.org/community-ecology-from-patterns-to-principles)
:::

### Introduction to Hierarchical Modeling

Federal University of Rio Grande do Sul (UFRGS)

Porto Alegre, RS, Brazil

2019

::: concise
- 45 h 
- [course](http://ferrazlab.org/graduate)
:::

### Geoprocessing with GRASS GIS

São Paulo State University (UNESP)

Rio Claro, SP, Brazil

2016

::: concise
- 24 h 
:::

### V Southern-Summer School on Mathematical Biology

São Paulo State University (UNESP)

São Paulo, SP, Brazil

2016

::: concise
- 53 h
- [course](https://www.ictp-saifr.org/v-southern-summer-school-on-mathematical-biology/)
:::

### Biology and conservation of amphibians and reptiles

Instituto Boitatá, IBEC

Alfenas, MG, Brazil

2015

::: concise
- 44 h 
:::

### Ecological data analysis with R

São Paulo State University (UNESP)

Rio Claro, SP, Brazil

2011

::: concise
- 40 h 
:::

Scholarship & Awards {data-icon=award}
--------------------------------------------------------------------------------

### Doctoral Graduate Scholarship

São Paulo Research Foundation (FAPESP) (BRL 91,002.24)  
São Paulo State University (UNESP)  
Grant [#2022/01899-6](https://bv.fapesp.br/en/bolsas/203713/landscape-structure-as-a-predictor-of-taxonomic-and-functional-diversity-of-amphibians-in-the-atlant/)

Rio Claro, SP, Brazil

2022 - 2024

**Title**: Landscape structure as a predictor of taxonomic and functional diversity of amphibians in the Atlantic Forest  
**Aim**:  1) how the structure of landscapes is configured throughout the Atlantic Forest Biome, 2) how the structure of the landscape affects the taxonomic and functional diversity of species in general, and 3) analyze this same question of species-specific mode, in addition to analyzing co-occurrences

### Master Graduate Scholarship

São Paulo Research Foundation (FAPESP) (BRL 16,248.54)  
São Paulo State University (UNESP)  
Grant [#2017/09676-8](https://bv.fapesp.br/en/bolsas/172826/effect-of-landscape-modifications-and-climate-changes-on-the-persistence-of-amphibians-in-the-atlant/)

Rio Claro, SP, Brazil

2017 - 2018

**Title**: Effect of Landscape Modifications and Climate Changes on the Persistence of Amphibians in the Atlantic Forest  
**Aim**: (1) to present an assessment of the surveys of the amphibian communities for the Atlantic Forest, their composition and distribution; (2) to investigate how habitat loss and fragmentation on the regional scale can affect the current persistence of amphibians from different reproductive guilds; and (3) to investigate how climate change may affect the future persistence of amphibians of the genus *Brachycephalus*, considered highly sensitive to these climatic changes

### Scientific Initiation Scholarship

São Paulo Research Foundation (FAPESP) (BRL 10,539.87)  
São Paulo State University (UNESP)  
Grant [#2013/02883-7](https://bv.fapesp.br/en/bolsas/142421/effect-of-fragmentation-on-the-persistence-of-anuran-amphibians-amphibia-anura-within-the-atlanti/)

Rio Claro, SP, Brazil

2013 - 2015

**Title**: Effect of fragmentation on the persistence of anuran amphibians (Amphibia: Anura) within the Atlantic Forest  
**Aim**: (1) model the potential distribution based on the environmental suitability of the species of interest; (2) identify landscapes with high environmental suitability and surveys with high sampling effort in order to characterize the regional anurofauna; and (3) evaluate the relative contribution of landscape indices (percentage of forest cover, connectivity, relief and urban proximity) to the persistence of species using model selection for multiple competing hypotheses based on Akaike information theory

Research Experience {data-icon=laptop}
--------------------------------------------------------------------------------

### Research Assistant

São Paulo State University (UNESP)  
[Spatial Ecology and Conservation Lab (LEEC)](https://ib.rc.unesp.br/#!/departamentos/ecologia/leec/home/)

Rio Claro, SP, Brazil

2015 - 2016

Statistical and spatial analyzes of mammal and ants biodiversity in the Atlantic Forest Biome

::: concise
- 2000 h 
:::

::: aside
From 2015 to 2016, I was a Research Assistant of Prof. Milton Cezar Ribeiro where I developed statistical and spatial analysis of mammal and ants biodiversity in the Atlantic Forest Biome
:::


Professional Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

### Environmental consultant

[Seleção Natural](http://selecaonatural.net/)

Piracicaba, SP, Brasil

2021 - 2022

::: concise
- Ecological Modeling
:::

::: aside
Since 2016, I have worked as an autonomous environmental consultant in the field of geoprocessing, analysis of ecological data, landscape ecology and species distribution modeling
:::

### Environmental consultant

[Seleção Natural](http://selecaonatural.net/)

Piracicaba, SP, Brazil

2020 - 2021

::: concise
- Ecological corridors
- Landscape metrics
- LSCorridors
- LSMetrics
:::

### Environmental consultant

[PROECO Ambiental](http://www.proecoambiental.com.br/)

Poços de Caldas, MG, Brasil

2019 - 2021

::: concise
- Species distribution modeling 
:::

### Environmental consultant

[Seleção Natural](http://selecaonatural.net/)

Piracicaba, SP, Brazil

2018 - 2019

::: concise
- Ecological data analyst
:::

### Environmental consultant

[Aquaflora](https://joao006.wixsite.com/consaquaflora)

Curitiba, PR, Brazil

2018 - 2019

::: concise
- Species distribution modeling 
:::

::: aside
Between 2018 and 2019, I composed a group of analysts to assess the impact of the Fundão dam rupture in Marina/MG (Brazil) on the Rio Doce Basin, where I compiled land cover information and built models for the distribution of terrestrial and aquatic species to several scenarios
:::

### Environmental consultant

Associação de Levantamento Florestal do Amazonas

Manaus, AM, Brazil

2018 - 2019

::: concise
- Shiny App
:::

### Environmental consultant

ECOnecta

Rio Claro, SP, Brazil

2018 - 2019

::: concise
- SIG specialist
- GRASS GIS
:::

### Environmental consultant

[Geoinform](http://www.geoinform.com.br/)

Rio Claro, SP, Brazil

2015 - 2016

::: concise
- Herpetology field assistant
:::

Teaching Experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

### <u>Courses</u>

Total hours:  
Graduate: 300 h  
Undergraduate: 102 h

N/A

N/A

::: aside
Since my formation I develop teaching activities, initially as a monitor. From the master's degree, I help and minister undergraduate and graduate courses, especially those related to Space Ecology, Species Distribution Models, Statistical Models in Ecology and Geoprocessing.
:::

### 9. Introduction to the use of geospatial data in R

Invited teacher  
Ecology, Biodiversity and Evolution Graduate Program  
São Paulo State University (UNESP)

Rio Claro, SP, Brazil

2021

::: concise
- 60 h
- [material](https://github.com/mauriciovancine/course-geospatial-data-r)
:::

### 8. Introduction to geospatial analysis with R

Invited teacher  
Ecology, Biodiversity and Evolution Graduate Program  
São Paulo State University (UNESP)

Rio Claro, SP, Brazil

2020

::: concise
- 60 h 
- [material](https://mauriciovancine.github.io/disciplina-analise-geoespacial-r/)
:::

### 7. Statistical Models in Ecology

Teacher  
Ecology Undergraduate  
São Paulo State University (UNESP)

Rio Claro, SP, Brazil

2020

::: concise
- 30 h 
:::

### 6. Introduction to Geoprocessing for Ethnobiology and Biodiversity Conservation

Invited external teacher  
Ethnobiology and Nature Conservation Graduate Program  
Rural Federal University of Pernambuco (UFRPE)

Recife, PE, Brazil

2019

::: concise
- 45 h
- [material](https://github.com/mauriciovancine/disciplina-geoprocessamento)
:::

### 5. Statistical Models in Ecology

Teaching assistant  
Ecology Undergraduate  
São Paulo State University (UNESP)

Rio Claro, SP, Brazil

2018

::: concise
- 12 h 
:::

### 4. Ecological Niche Modeling: theory and practice

Teaching assistant  
Ecology and Biodiversity Graduate Program  
São Paulo State University (UNESP)

Rio Claro, SP, Brazil

2017

::: concise
- 60 h 
:::

### 3. Ecological Niche Modeling: theory and practice

Teaching assistant  
Ecology Graduate Program  
The University of Campinas (UNICAMP)

Campinas, SP, Brazil

2016

::: concise
- 45 h 
:::

### 2. Ecological Niche Modeling in R

Teaching assistant  
Ecology and Biodiversity Graduate Program  
São Paulo State University (UNESP)

Rio Claro, SP, Brazil

2016

::: concise
- 30 h 
:::

### 1. Quantitative Ecology

Teaching assistant  
Ecology Undergraduate  
São Paulo State University (UNESP)

Rio Claro, SP, Brazil

2015

::: concise
- 60 h 
:::


### <u>Workshops</u>

Total hours: 95 h

N/A

N/A

::: aside
Since 2014, I teach practical training courses, mainly related to the R language and Species Distribution Models
:::

### 11. Introduction to the R language for data manipulation and visualization

Short course instructor  
[XXXI Ecology Studies Week](http://www.rc.unesp.br/see/)  
São Paulo State University (UNESP)

Online

2021

::: concise
- 08 h
- [material](https://github.com/mauriciovancine/workshop-r-introduction)
:::

### 10. Geoprocessing with QGIS

Short course instructor  
[32ª Biology Studies Week](https://www.facebook.com/SEBioRC/)  
São Paulo State University (UNESP)

Online

2021

::: concise
- 03 h
- [material](https://github.com/mauriciovancine/workshop-qgis)
:::

### 9. Introduction to species distribution modeling using the R language

Workshop instructor  
[Mastozóologos Organizados em uma Conferência Online (MOCÓ)](https://moco2021.com.br/)  
Sociedade Brasileira de Mastozoologia

Online

2021

::: concise
- 06 h
- [material](https://github.com/mauriciovancine/workshop-r-sdm)
:::

### 8. Introduction to R Language

Short course instructor  
[XXX Ecology Studies Week](http://www.rc.unesp.br/see/)  
São Paulo State University (UNESP)

Rio Claro, SP, Brazil

2019

::: concise
- 08 h
- [material](https://github.com/mauriciovancine/r-minicurso-see-2019)
:::

### 7. Introduction to R Language

Short course instructor  
[30ª Biology Studies Week](https://www.facebook.com/SEBioRC/)  
São Paulo State University (UNESP)

Rio Claro, SP, Brazil

2019

::: concise
- 08 h
- [material](https://github.com/mauriciovancine/r-minicurso-sebio-2019)
:::

### 6. Introduction to Species Distribution Modeling using R Language: theory and practice

Short course instructor  
[9º Brazilian Congress of Herpetology](https://9cbh.galoa.com.br/)  
The University of Campinas (UNICAMP)

Campinas, SP, Brazil

2019

::: concise
- 07 h
- [material](https://github.com/mauriciovancine/r-minicurso-sdm-9-cbh)
:::

### 5. Field work with amphibians

Short course instructor  
[29ª Biology Studies Week](https://www.facebook.com/SEBioRC/)  
São Paulo State University (UNESP)

Rio Claro, SP, Brazil

2018

::: concise
- 08 h 
:::

### 4. Field herpetology

Short course instructor  
[XXVII Ecology Studies Week](http://www.rc.unesp.br/see/)  
São Paulo State University (UNESP)

Rio Claro, SP, Brazil

2016

::: concise
- 15 h 
:::

### 3. Introduction to software R: data management, graphs and statistical analysis

Short course instructor  
[XXVII Ecology Studies Week](http://www.rc.unesp.br/see/)  
São Paulo State University (UNESP)

Rio Claro, SP, Brazil

2016

::: concise
- 16 h 
:::

### 2. Introduction to software R

Short course instructor  
[XXVI Ecology Studies Week](http://www.rc.unesp.br/see/)  
São Paulo State University (UNESP)

Rio Claro, SP, Brazil

2015

::: concise
- 08 h 
:::

### 1. Organization of data in electronic sheets - Calc

Short course instructor  
[XXV Ecology Studies Week](http://www.rc.unesp.br/see/)  
São Paulo State University (UNESP)

Rio Claro, SP, Brazil

2014

::: concise
- 08 h 
:::

Books {data-icon=book}
--------------------------------------------------------------------------------

### 1. Ecological Analisys in R

*Nupeea* Recife, PE. 640 p

N/A

2022

ISBN: 978-85-7917-564-0
<br>
Site: https://analises-ecologicas.com/
<br>
Da Silva FR, Gonçalves-Souza T, Paterno GB, Provete DB, <u>**Vancine MH**</u>

Publications {data-icon=file}
--------------------------------------------------------------------------------

### 23. Mammals in São Paulo State: diversity, distribution, ecology, and conservation

*Biota Neotropica*, 22(spe): e20221363

N/A

2022

DOI: [10.1590/1676-0611-BN-2022-1363](https://doi.org/10.1590/1676-0611-BN-2022-1363)
<br>
Galetti M, Carmignotto AP, Percequillo AR, Santos MCO, Ferraz KMPMB, Lima F, **<u>Vancine MH**</u>, Muylaert RL, Bonfim FCG, Magioli M, Abra FD, Chiarello AG, Duarte JMB, Morato R, Beisiegel BM, Olmo F, Galetti Jr. PM, Ribeiro MC

::: aside
**Citations**  
[Publons](https://publons.com/researcher/F-7305-2016/)  
[Scopus](https://www.scopus.com/authid/detail.uri?authorId=57193451888)  
[Google Scholar](https://scholar.google.com/citations?user=i-2xZBQAAAAJ)  
:::

### 22. The fate of vegetation remnants  in the southern Amazon's largest threatened hotspot: part (I) a 33-year analysis of LULCC in the Tapajos River basin, Brazil

*Research, Society and Development*, 11(10), e448111032553

N/A

2022

DOI: [10.33448/rsd-v11i10.32553](https://doi.org/10.33448/rsd-v11i10.32553)
<br>
Borges GA, Mancilla G, Siqueira AB, **<u>Vancine MH**</u>, Ribeiro MC, Maia JCS 

### 21. Present and future distribution of bat hosts of sarbecoviruses: implications for conservation and public health

*Proceedings of the Royal Society B* 289(1975), 20220397

N/A

2022

DOI: [10.1098/rspb.2022.0397](https://doi.org/10.1098/rspb.2022.0397)
<br>
Muylaert RL, Kingston T, Luo J, **<u>Vancine MH**</u>, Galli N, Carlson CJ, John RS, Rulli MC, Hayman DT

### 20. Climate change impacts on the Copernicia alba and Copernicia prunifera (Arecaceae) distribution in South America

*Brazilian Journal of Botany* 45, 807–818.

N/A

2022

DOI: [10.1007/s40415-022-00801-8](https://doi.org/10.1007/s40415-022-00801-8)
<br>
Costa MF, Francisconi AF, <u>**Vancine MH**</u>, Zucchi MI 

### 19. Effects of climate change on distribution and areas that protect two neotropical marsupials associated with aquatic environments

*Ecological Informatics* 68:101570

N/A

2022

DOI: [10.1016/j.ecoinf.2022.101570](https://doi.org/10.1016/j.ecoinf.2022.101570)
<br>
Ribeiro-Souza P, Graipel ME, Astúa D, <u>**Vancine MH**</u>, Pires JS

### 18. Forest cover and connectivity have pervasive effects on the maintenance of evolutionary distinct interactions in seed dispersal networks

*Oikos* 2022(2):oik.08240

N/A

2022

DOI: [10.1111/oik.08240](https://doi.org/10.1111/oik.08240)
<br>
Monteiro ECS, Pizo MA, <u>**Vancine MH**</u>, Ribeiro MC

### 17. Invasive wild boar’s distribution overlap with threatened native ungulate in Patagonia

*Journal of Mammalogy* 102(5):1298-1308

N/A

2021

DOI: [10.1093/jmammal/gyab099](https://doi.org/10.1093/jmammal/gyab099)
<br>
Bercê W, Bello C, Mendes CP, <u>**Vancine MH**</u>, Galetti M, Ballaru SA

### 16. Setting Priority Conservation Management Regions to Reverse Rapid Range Decline of a Key Neotropical Forest Ungulate

*Global Ecology and Conservation* 31:e01796

N/A

2021

DOI: [10.1016/j.gecco.2021.e01796](https://doi.org/10.1016/j.gecco.2021.e01796)
<br>
Oshima JEF, Jorge MLSP, Sobral-Souza T, Börger L, Keuroghlian A, Peres CA, <u>**Vancine MH**</u>, Collen B, Ribeiro MC

### 15. Distribution of macroalgal epiphytes and host species from the Cuban marine shelf inferred from ecological modelling

*Aquatic Botany* 172:103395

N/A

2021

DOI: [10.1016/j.aquabot.2021.103395](https://doi.org/10.1016/j.aquabot.2021.103395)
<br>
Jover A, Cabrera A, Ramos A, <u>**Vancine MH**</u>, Suárez AM, Machell J, Perez-Llórens JL

### 14. Future climate change will impact the size and location of breeding and wintering areas of migratory thrushes in South America

*The Condor: Ornithological Applications* 123:1-16

N/A

2021

DOI: [10.1093/ornithapp/duab006](https://doi.org/10.1093/ornithapp/duab006)
<br>
Da Silveira NS, <u>**Vancine MH**</u>, Jahn AE, Pizo MA, Sobral-Souza T

### 13. Host diversity outperforms climate as a global driver of symbiont diversity in the bird‐feather mite system

*Diversity and Distributions* 27(3):416-426

N/A

2021

DOI: [10.1111/ddi.13201](https://doi.org/10.1111/ddi.13201)
<br>
Gusmão RAF, Hernandes FRA, <u>**Vancine MH**</u>, Naka LN, Doña J, Gonçalves-Souza T

### 12. Environmental niche and functional role similarity between invasive and native palms in the Atlantic Forest

*Biological Invasions* 21:741-754

N/A

2021

DOI: [10.1007/s10530-020-02400-8](https://doi.org/10.1007/s10530-020-02400-8)
<br>
Bello C, Cintra ALP, Barreto E, <u>**Vancine MH**</u>, Sobral-Souza T, Graham CH, Galetti M

### 11. Effects of landscape modification on species richness patterns of fruit-feeding butterflies in Brazilian Atlantic Forest

*Diversity and Distributions* 26(2):196-208

N/A

2020

DOI: [10.1111/ddi.13007](https://doi.org/10.1111/ddi.13007)
<br>
Santos JP, Sobral-Souza T, Brown Jr KS, <u>**Vancine MH**</u>, Ribeiro MC, Freitas AVL

### 10. Fragmented tropical forests lose mutualistic plant-animal interactions

*Diversity and Distributions* 26(2):154-168

N/A

2020

DOI: [10.1111/ddi.13010](https://doi.org/10.1111/ddi.13010)
<br>
Marjakangas E, Abrego N, Grøtan V, Lima RAF, Bello C, Bovendorp RS, Culot L, Hasui E, Muylaert RL, Lima F, Niebuhr B, Oliveira AA, Pereira L, Prado I, Stevens RD, <u>**Vancine MH**</u>, Ribeiro MC, Galetti M, Ovaskainen O

### 9. Predicting the potential hybridization zones between native and invasive marmosets within Neotropical biodiversity hotspots

*Global Ecology and Conservation* 20:e00706

N/A

2019

DOI: [10.1016/j.gecco.2019.e00706](https://doi.org/10.1016/j.gecco.2019.e00706)
<br>
Moraes AM, <u>**Vancine MH**</u>, Moraes AM, Cordeiro CLO, Pinto MP, Lima AA, Culot L, Silva TSF, Collevatti RG, Ribeiro MC, Sobral-Souza T

### 8. Land-use changes and the expansion of biofuel crops threaten the giant anteater in southeastern Brazil

*Journal of Mammalogy* 100(2):435–444

N/A

2019

DOI: [10.1093/jmammal/gyz042](https://doi.org/10.1093/jmammal/gyz042)
<br>
Bertassoni A, Costa RT, Gouvea JA, Bianchi BC, Ribeiro JW, <u>**Vancine MH**</u>, Ribeiro MC

### 7. Spatial prediction of risk areas for vector transmission of Trypanosoma cruzi in the State of Paraná, southern Brazil

*PLOS Neglected Tropical Diseases* 12(10):e0006907

N/A

2018

DOI: [10.1371/journal.pntd.0006907](https://doi.org/10.1371/journal.pntd.0006907)
<br>
Ferro e Silva AM, Sobral-Souza T, <u>**Vancine MH**</u>, Muylaert RL, Abreu AP, Pelloso SM, Carvalho MDB, Andrade L, Ribeiro MC, Toledo MJO 

### 6. A note on the territorial limits of the Atlantic Forest

*Oecologia Australis* 22(3):302–311

N/A

2018

DOI: [10.4257/oeco.2018.2203.09](https://doi.org/10.4257/oeco.2018.2203.09)
<br>
Muylaert RL, <u>**Vancine MH**</u>, Bernardo R, Oshima JEF, Sobral-Souza T, Tonett VR, Niebuhr BBS, Ribeiro MC

### 5. ATLANTIC AMPHIBIANS: a data set of amphibian communities from the Atlantic Forests of South America

*Ecology* 99(7):1692–1692

N/A

2018

DOI: [10.1002/ecy.2392](https://doi.org/10.1002/ecy.2392)
<br>
<u>**Vancine MH**</u>, Duarte KS, Souza YS, Giovanelli JGR, Sobrinho PMM, López A, Bovo RP, Maffei F, Lion MB, Ribeiro-Júnior JW, Brassaloti R, Ortiz C, Sawakuchi HO, Forti LR, Cacciali P, Bertoluci J, Haddad CFB, Ribeiro MC

### 4. Efficiency of protected areas in Amazon and Atlantic Forest conservation: A spatio-temporal view

*Acta Oecologica* 87:1–7

N/A

2018

DOI: [10.1016/j.actao.2018.01.001](https://doi.org/10.1016/j.actao.2018.01.001)
<br>
Sobral-Souza T, <u>**Vancine MH**</u>, Ribeiro MC, Lima-Ribeiro MS

### 3. Forest cover influences occurrence of mammalian carnivores within Brazilian Atlantic Forest

*Journal of Mammalogy* 98:1721–1731

N/A

2017

DOI: [10.1093/jmammal/gyx103](https://doi.org/10.1093/jmammal/gyx103)
<br>
Regolin AL, Cherem JJ, Graipel ME, Bogoni JA, Ribeiro JW, <u>**Vancine MH**</u>, Tortato MA, Oliveira-Santos LG, Fantacini FM, Luiz MR, Castilho PV, Ribeiro MC, Cáceres, NC

### 2. Impacts of mining activities on the potential geographic distribution of eastern Brazil mountaintop endemic species. 

*Perspectives in Ecology and Conservation* 15(3):172–178

N/A

2017

DOI: [10.1016/j.pecon.2017.07.005](https://doi.org/10.1016/j.pecon.2017.07.005)
<br>
De Castro Pena J, Goulart F, Fernandes GW, Hoffmann D, Leite FSF, Santos NB, Soares-Filho B, Sobral-Souza T, <u>**Vancine MH**</u>, Rodrigues M

### 1. High mammal species turnover in forest patches immersed in biofuel plantations

*Biological Conservation* 210:352–359

N/A

2017

DOI: [10.1016/j.biocon.2017.02.033](https://doi.org/10.1016/j.biocon.2017.02.033)
<br>
Beca G, <u>**Vancine MH**</u>, Carvalho CS, Pedrosa F, Alves RSC, Buscariol D, Peres CA, Ribeiro MC, Galetti M
