---
title: "Maurício Vancine"
author: Maurício Vancine
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: true
    css: resume.css
---

Aside
================================================================================

Contato {#contact}
--------------------------------------------------------------------------------
- `r icons::fontawesome("link")` [mauriciovancine.github.io](https://mauriciovancine.github.io/)
- `r icons::fontawesome("envelope", style = "solid")` mauricio.vancine@gmail.com
- `r icons::fontawesome("twitter")` [mauriciovancine](https://twitter.com/mauriciovancine)
- `r icons::fontawesome("github")` [github/mauriciovancine](https://github.com/mauriciovancine)
- `r icons::academicons("orcid")` [0000-0001-9650-7575](https://orcid.org/0000-0001-9650-7575)
- `r icons::academicons("lattes")` [9761288418931193](http://lattes.cnpq.br/9761288418931193)

Temas {#themes}
--------------------------------------------------------------------------------
- `r icons::fontawesome("globe")` `Ecologia Espacial`
- `r icons::fontawesome("globe-americas")` `Ecologia da Paisagem`
- `r icons::fontawesome("chart-bar")` `Modelagem Ecológica`
- `r icons::fontawesome("layer-group")` `Geoprocessamento`
- `r icons::fontawesome("frog")` `Ecologia de anfíbios`

Habilidades {#skills}
--------------------------------------------------------------------------------
- `r icons::fontawesome("r-project")` [`R`](https://www.r-project.org/)
- `r icons::fontawesome("laptop-code")` [`tidyverse`](https://www.tidyverse.org/)
- `r icons::fontawesome("markdown")` [`markdown`](https://daringfireball.net/projects/markdown/)
- `r icons::fontawesome("code-branch")` [`git (básico)`](https://git-scm.com/)
- `r icons::fontawesome("python")` [`python (básico)`](https://www.python.org/)
- `r icons::fontawesome("terminal")` [`bash (básico)`](https://www.gnu.org/software/bash/)
- `r icons::fontawesome("quora")` [`QGIS`](https://qgis.org/en/site/)
- `r icons::fontawesome("seedling")` [`GRASS GIS`](https://grass.osgeo.org/)
- `r icons::fontawesome("linux")` [`GNU/Linux`](https://www.gnu.org/gnu/linux-and-gnu.html)

Línguas {#languages}
--------------------------------------------------------------------------------
- Português (Falante nativo)
- Inglês (Intermediário)
- Espanhol (Básico)

<i class='fas fa-file-pdf'></i> [Download PDF](https://mauriciovancine.github.io/cv/cv-mauricio-vancine-pt-academic-short.pdf)
<br>
<i class='fas fa-download'></i> [Versão completa](https://mauriciovancine.github.io/cv/cv-mauricio-vancine-pt-academic-complete.html)

Disclaimer
------------------------------------
CV pelo pacote [**pagedown**](https://github.com/rstudio/pagedown).  
Código em `r icons::fontawesome("github")` [GitHub](https://github.com/mauriciovancine/cv).  
Atualizado em `r Sys.Date()`.

Main
================================================================================

Maurício Vancine {#title}
--------------------------------------------------------------------------------

### Ecólogo e Doutorando em Ecologia, Evolução e Biodiversidade

Sou Ecólogo e Doutorando na Unesp Rio Claro, Brasil. Possuo experiência em ecologia da paisagem, efeitos da perda e fragmentação de habitat, ecologia de anfíbios, modelagem de distribuição de espécies, e análise de dados ecológicos e geoespaciais.

Formação {data-icon=graduation-cap}
--------------------------------------------------------------------------------

### Universidade Estadual Paulista (UNESP), Rio Claro, SP

[Doutorando em Ecologia, Evolução e Biodiversidade](https://ib.rc.unesp.br/#!/pos-graduacao/secao-tecnica-de-pos/programas/ecologia-e-biodiversidade/apresentacao-novo/)

N/A

2020 - Presente

### Universidade Estadual Paulista (UNESP), Rio Claro, SP

[Mestre em Zoologia](https://ib.rc.unesp.br/#!/pos-graduacao/secao-tecnica-de-pos/programas/zoologia/), [**Bolsa FAPESP**: 2017/09676-8](https://bv.fapesp.br/en/bolsas/172826/effect-of-landscape-modifications-and-climate-changes-on-the-persistence-of-amphibians-in-the-atlant/)

N/A

2016 - 2018

### Universidade Estadual Paulista (UNESP), Rio Claro, SP

[Bacharel em Ecologia](https://ib.rc.unesp.br/#!/graduacao/cursos-conselho-de-curso/ecologia/), [**Bolsa FAPESP**: 2013/02883-7](https://bv.fapesp.br/en/bolsas/142421/effect-of-fragmentation-on-the-persistence-of-anuran-amphibians-amphibia-anura-within-the-atlanti/)

N/A

2011 - 2014

Formação Complementar {data-icon=chalkboard}
--------------------------------------------------------------------------------

### Hierarchical Modelling of Species Communities with Hmsc (45 h)

Universidade de Jyväskylä (Online), Helsinki, Finlândia

N/A

2022

### Jornada Data Science (330 h)

Ômega Data Science (Online)

N/A

2022

### Hierarchical Modelling of Species Communities with Hmsc (25 h)

Universidade de Helsinki (Online), Helsinki, Finlândia

N/A

2020

### School on Community Ecology: from patterns to principles (60 h)

Universidade Estadual Paulista (UNESP), São Paulo, SP, Brasil

N/A

2020

### Introdução à Modelagem Hierárquica (45 h)

Universidade Federal do Rio Grande do Sul (UFRGS), Porto Alegre, RS

N/A

2019

### Geoprocessamento com GRASS GIS (24 h)

Universidade Estadual Paulista (UNESP), Rio Claro, SP

N/A

2016

### V Escola de verão de biologia matemática (53 h)

Universidade Estadual Paulista (UNESP), São Paulo, SP

N/A

2016

Experiência em Pesquisa {data-icon=laptop}
--------------------------------------------------------------------------------

### Assistente de Pesquisa (2000 h)

Universidade Estadual Paulista (UNESP)  
[Laboratório de Ecologia Espacial e Conservação (LEEC)](https://ib.rc.unesp.br/#!/departamentos/ecologia/leec/home/), Rio Claro, SP, Brasil

N/A

2015 - 2016

Publicações {data-icon=file}
--------------------------------------------------------------------------------

### [Publons](https://publons.com/researcher/F-7305-2016/)

N/A

N/A

N/A

### [Scopus](https://www.scopus.com/authid/detail.uri?authorId=57193451888) 

N/A

N/A

N/A

### [Google Scholar](https://scholar.google.com/citations?user=i-2xZBQAAAAJ)

N/A

N/A

N/A
