---
title: "Maurício Vancine"
author: Maurício Vancine
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: true
    css: resume.css
---

Aside
================================================================================

<i class='fas fa-file-pdf'></i> [Download PDF](https://mauriciovancine.github.io/cv/cv-mauricio-vancine-en-academic-short.pdf)
<br>
<i class='fas fa-download'></i> [Complete version](https://mauriciovancine.github.io/cv/cv-mauricio-vancine-en-academic-complete.html)

Contact {#contact}
--------------------------------------------------------------------------------
- `r icons::fontawesome("link")` [mauriciovancine.github.io](https://mauriciovancine.github.io/)
- `r icons::fontawesome("envelope", style = "solid")` mauricio.vancine@gmail.com
- `r icons::fontawesome("twitter")` [mauriciovancine](https://twitter.com/mauriciovancine)
- `r icons::fontawesome("github")` [github/mauriciovancine](https://github.com/mauriciovancine)
- `r icons::academicons("orcid")` [0000-0001-9650-7575](https://orcid.org/0000-0001-9650-7575)
- `r icons::academicons("lattes")` [9761288418931193](http://lattes.cnpq.br/9761288418931193)

Themes {#contact}
--------------------------------------------------------------------------------
- `r icons::fontawesome("globe")` `Spatial Ecology`
- `r icons::fontawesome("globe-americas")` `Landscape Ecology`
- `r icons::fontawesome("chart-bar")` `Ecological Modeling`
- `r icons::fontawesome("layer-group")` `Geoprocessing`
- `r icons::fontawesome("frog")` `Amphibian Ecology`

Skills {#skills}
--------------------------------------------------------------------------------
- `r icons::fontawesome("r-project")` [`R`](https://www.r-project.org/)
- `r icons::fontawesome("laptop-code")` [`tidyverse`](https://www.tidyverse.org/)
- `r icons::fontawesome("markdown")` [`markdown`](https://daringfireball.net/projects/markdown/)
- `r icons::fontawesome("code-branch")` [`git (básico)`](https://git-scm.com/)
- `r icons::fontawesome("python")` [`python (básico)`](https://www.python.org/)
- `r icons::fontawesome("terminal")` [`bash (básico)`](https://www.gnu.org/software/bash/)
- `r icons::fontawesome("quora")` [`QGIS`](https://qgis.org/en/site/)
- `r icons::fontawesome("seedling")` [`GRASS GIS`](https://grass.osgeo.org/)
- `r icons::fontawesome("linux")` [`GNU/Linux`](https://www.gnu.org/gnu/linux-and-gnu.html)

Languages {#skills}
--------------------------------------------------------------------------------
- Portuguese (Native speaker)
- English
- Spanish

Disclaimer
------------------------------------
CV by [**pagedown**](https://github.com/rstudio/pagedown) R package.  
Code available on `r icons::fontawesome("github")` [GitHub](https://github.com/mauriciovancine/cv).  
Last updated on `r Sys.Date()`.

Main
================================================================================

Maurício Vancine {#title}
--------------------------------------------------------------------------------

### Spatial Ecologist and Doctoral Student in Ecology, Evolution and Biodiversity

I am a Spatial Ecologist and PhD student at Unesp Rio Claro, Brazil. I have experience in landscape ecology, habitat loss and fragmentation, amphibian ecology, species distribution modeling, and analysis of ecological and spatial data.

Education {data-icon=graduation-cap}
--------------------------------------------------------------------------------

### São Paulo State University (UNESP), Rio Claro, SP, Brazil

[Doctoral Student in Ecology, Evolution and Biodiversity](https://ib.rc.unesp.br/#!/pos-graduacao/secao-tecnica-de-pos/programas/ecologia-e-biodiversidade/apresentacao-novo/)

N/A

2020 - Present

### São Paulo State University (UNESP), Rio Claro, SP, Brazil

[Master in Zoology](https://ib.rc.unesp.br/#!/pos-graduacao/secao-tecnica-de-pos/programas/zoologia/), [**Grant FAPESP**: #2017/09676-8](https://bv.fapesp.br/en/bolsas/172826/effect-of-landscape-modifications-and-climate-changes-on-the-persistence-of-amphibians-in-the-atlant/)

N/A

2016 - 2018

### São Paulo State University (UNESP), Rio Claro, SP, Brazil

[Bachelor in Ecology](https://ib.rc.unesp.br/#!/graduacao/cursos-conselho-de-curso/ecologia/), [**Grant FAPESP**: #2013/02883-7](https://bv.fapesp.br/en/bolsas/142421/effect-of-fragmentation-on-the-persistence-of-anuran-amphibians-amphibia-anura-within-the-atlanti/)

N/A

2011 - 2014

Complementary Education {data-icon=book}
--------------------------------------------------------------------------------

### Hierarchical Modelling of Species Communities with Hmsc (25 h)

University of Helsinki (Zoom), Helsinki, Finland

N/A

2020

### School on Community Ecology: from patterns to principles (60 h)

São Paulo State University (UNESP), São Paulo, SP, Brazil

N/A

2020

### Introduction to Hierarchical Modeling (45 h)

Federal University of Rio Grande do Sul (UFRGS), Porto Alegre, RS, Brazil

N/A

2019

### Geoprocessing with GRASS GIS (24 h)

São Paulo State University (UNESP), Rio Claro, SP, Brazil

N/A

2016

### V Southern-Summer School on Mathematical Biology  (53 h)

São Paulo State University (UNESP), São Paulo, SP, Brazil

N/A

2016

Research Experience {data-icon=laptop}
--------------------------------------------------------------------------------

### Research Assistant (2000 h)

São Paulo State University (UNESP)  
[Spatial Ecology and Conservation Lab (LEEC)](https://ib.rc.unesp.br/#!/departamentos/ecologia/leec/home/), Rio Claro, SP, Brazil

N/A

2015 - 2016

Publications {data-icon=file}
--------------------------------------------------------------------------------

### [Publons](https://publons.com/researcher/F-7305-2016/)

N/A

N/A

N/A

### [Scopus](https://www.scopus.com/authid/detail.uri?authorId=57193451888) 

N/A

N/A

N/A

### [Google Scholar](https://scholar.google.com/citations?user=i-2xZBQAAAAJ)

N/A

N/A

N/A