---
title: "Maurício Vancine"
author: Maurício Vancine
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: true
    css: resume.css
---

Aside
================================================================================

Contact {#contact}
--------------------------------------------------------------------------------
- `r icon::fontawesome("link")` [mauriciovancine.github.io](https://mauriciovancine.github.io/)
- `r icon::fontawesome("envelope", style = "solid")` mauricio.vancine@gmail.com
- `r icon::fontawesome("twitter")` [mauriciovancine](https://twitter.com/mauriciovancine)
- `r icon::fontawesome("github")` [github/mauriciovancine](https://github.com/mauriciovancine)

Themes {#contact}
--------------------------------------------------------------------------------
- `r icon::fontawesome("globe-americas")` `Spatial Ecology`  
- `r icon::fontawesome("globe-americas")` `Landscape Ecology`  
- `r icon::fontawesome("chart-line")` `Ecology Modelling`  
- `r icon::fontawesome("chart-line")` `Species Distribution Modelling (SDM)`  
- `r icon::fontawesome("globe")` `Geoprocessing`  
- `r icon::fontawesome("chalkboard-teacher")` `Teaching Ecology, Statistics and R`

Programming {#contact}
--------------------------------------------------------------------------------
- `r icon::fontawesome("r-project")` [`R`](https://www.r-project.org/)  
- `r icon::fontawesome("laptop-code")` [`tidyverse`](https://www.tidyverse.org/)  
- `r icon::fontawesome("markdown")` [`markdown`](https://daringfireball.net/projects/markdown/)  
- `r icon::fontawesome("code-branch")` [`Git`](https://git-scm.com/)  
- `r icon::fontawesome("python")` [`Python`](https://www.python.org/)  
- `r icon::fontawesome("terminal")` [`Bash`](https://www.gnu.org/software/bash/)

Software {#contact}
--------------------------------------------------------------------------------
- `r icon::fontawesome("globe")` [`QGIS`](https://qgis.org/en/site/)  
- `r icon::fontawesome("globe")` [`GRASS GIS`](https://grass.osgeo.org/)  
- `r icon::fontawesome("linux")` [`GNU/Linux`](https://www.gnu.org/gnu/linux-and-gnu.html)

Disclaimer
------------------------------------
CV by [**pagedown**](https://github.com/rstudio/pagedown) R package.  

Code available on <i class="fab fa-github"></i> [GitHub](https://github.com/mauriciovancine/cv). 

Last updated on `r Sys.Date()`.  

[Download a PDF of this CV](https://github.com/mauriciovancine/cv/raw/master/mauricio_vancine_cv.pdf)

Main
================================================================================

Maurício Vancine {#title}
--------------------------------------------------------------------------------

Ecologist and Doctoral Student in Ecology

Education {data-icon=graduation-cap}
--------------------------------------------------------------------------------

### São Paulo State University (UNESP)

[Doctoral Student in Ecology](https://ib.rc.unesp.br/#!/pos-graduacao/secao-tecnica-de-pos/programas/zoologia/)

Rio Claro, SP, Brazil

2020 - Present

**Thesis**: Effect of landscape changes on communities amphibians in the Atlantic Forest
<br>
**Advisor**: Prof. Milton Cezar Ribeiro

### São Paulo State University (UNESP)

[Master in Zoology](https://ib.rc.unesp.br/#!/pos-graduacao/secao-tecnica-de-pos/programas/zoologia/)

Rio Claro, SP, Brazil

2016 - 2018

**Thesis**: Diversity, distribution and effect of climate change on Atlantic Forest amphibian communities ([UNESP Libraries](https://repositorio.unesp.br/handle/11449/154993))
<br>
**Advisor**: Prof. Célio Fernando Baptista Haddad

### São Paulo State University (UNESP)

[Bachelor in Ecology](https://ib.rc.unesp.br/#!/graduacao/cursos-conselho-de-curso/ecologia/)

Rio Claro, SP, Brazil

2011 - 2015

**Thesis**: Effect of fragmentation on the persistence of anuran amphibians (Amphibia: Anura) within the Atlantic Forest ([UNESP Libraries](https://repositorio.unesp.br/handle/11449/138991))
<br>
**Advisor**: Prof. Milton Cezar Ribeiro

Complementary Education {data-icon=book}
--------------------------------------------------------------------------------

### Hierarchical Modelling of Species Communities with the R-package Hmsc

University of Helsinki

Helsinki, Finlândia

2020

::: concise
- 25 h 
:::

### School on Community Ecology: from patterns to principles

São Paulo State University (UNESP)

São Paulo, SP, Brazil

2020

::: concise
- 60 h 
:::

### Introduction to Hierarchical Modeling

Federal University of Rio Grande do Sul (UFRGS)

Porto Alegre, RS, Brazil

2019

::: concise
- 45 h 
:::

### Geoprocessing with GRASS GIS

São Paulo State University (UNESP)

Rio Claro, SP, Brazil

2016

::: concise
- 24 h 
:::

### V Southern-Summer School on Mathematical Biology

São Paulo State University (UNESP)

São Paulo, SP, Brazil

2016

::: concise
- 53 h 
:::

### Biology and conservation of amphibians and reptiles

Instituto Boitatá, IBEC

Alfenas, MG, Brazil

2015

::: concise
- 44 h 
:::

### Ecological data analysis with R

São Paulo State University (UNESP)

Rio Claro, SP, Brazil

2011

::: concise
- 40 h 
:::

Scholarship & Awards {data-icon=award}
--------------------------------------------------------------------------------

::: aside
My formation...
:::

### Doctoral Graduate Scholarship

Coordination of Superior Level Staff Improvement (Capes) (BRL 105,600.00)
<br>
São Paulo State University (UNESP)
<br>
Grant [88887.480959/2020-00]()

Rio Claro, SP, Brazil

2020 - 2024

**Title**: Effect of landscape changes on communities amphibians in the Atlantic Forest
<br>
**Aim**: Developing

### Master Graduate Scholarship

São Paulo Research Foundation (FAPESP) (BRL 16,248.54)
<br>
São Paulo State University (UNESP)
<br>
Grant [#2017/09676-8](https://bv.fapesp.br/en/bolsas/172826/effect-of-landscape-modifications-and-climate-changes-on-the-persistence-of-amphibians-in-the-atlant/)

Rio Claro, SP, Brazil

2017 - 2018

**Title**: Effect of Landscape Modifications and Climate Changes on the Persistence of Amphibians in the Atlantic Forest
<br>
**Aim**: (1) to present an assessment of the surveys of the amphibian communities for the Atlantic Forest, their composition and distribution; (2) to investigate how habitat loss and fragmentation on the regional scale can affect the current persistence of amphibians from different reproductive guilds; and (3) to investigate how climate change may affect the future persistence of amphibians of the genus *Brachycephalus*, considered highly sensitive to these climatic changes

### Scientific Initiation Scholarship

São Paulo Research Foundation (FAPESP) (BRL 10,539.87)
<br>
São Paulo State University (UNESP)
<br>
Grant [#2013/02883-7](https://bv.fapesp.br/en/bolsas/142421/effect-of-fragmentation-on-the-persistence-of-anuran-amphibians-amphibia-anura-within-the-atlanti/)

Rio Claro, SP, Brazil

2013 - 2015

**Title**: Effect of fragmentation on the persistence of anuran amphibians (Amphibia: Anura) within the Atlantic Forest
<br>
**Aim**: (1) model the potential distribution based on the environmental suitability of the species of interest; (2) identify landscapes with high environmental suitability and surveys with high sampling effort in order to characterize the regional anurofauna; and (3) evaluate the relative contribution of landscape indices (percentage of forest cover, connectivity, relief and urban proximity) to the persistence of species using model selection for multiple competing hypotheses based on Akaike information theory

Research Experience {data-icon=laptop}
--------------------------------------------------------------------------------

::: aside
My formation...
:::

### Research Assistant

São Paulo State University (UNESP)
<br>
[Spatial Ecology and Conservation Lab (LEEC)](https://ib.rc.unesp.br/#!/departamentos/ecologia/leec/home/)

Rio Claro, SP, Brazil

2015 - 2016

Statistical and spatial analyzes of mammal and ants biodiversity in the Atlantic Forest Biome

::: concise
- 2000 h 
:::

Professional Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

::: aside
My formation...
:::

### Environmental consultant

[Seleção Natural](http://selecaonatural.net/)

Piracicaba, SP, Brazil

2020

::: concise
- Ecological corridors
- Landscape metrics 
:::

### Environmental consultant

[PROECO Ambiental](http://www.proecoambiental.com.br/)

Poços de Caldas, MG, Brasil

2019 - 2021

::: concise
- Species distribution modeling 
:::

### Environmental consultant

[Seleção Natural](http://selecaonatural.net/)

Piracicaba, SP, Brazil

2018 - 2019

::: concise
- Ecological data analyst
:::

### Environmental consultant

[Aquaflora](https://joao006.wixsite.com/consaquaflora)

Curitiba, PR, Brazil

2018 - 2019

::: concise
- Species distribution modeling 
:::

### Environmental consultant

Associação de Levantamento Florestal do Amazonas

Manaus, AM, Brazil

2018 - 2019

::: concise
- Shiny App
:::

### Environmental consultant

ECOnecta

Rio Claro, SP, Brazil

2018 - 2019

::: concise
- SIG specialist
- GRASS GIS
:::

### Environmental consultant

[Geoinform](http://www.geoinform.com.br/)

Rio Claro, SP, Brazil

2015 - 2016

::: concise
- Herpetology field assistent
:::

Teaching Experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

::: aside
My formation...
:::

### <u>Courses</u>

N/A

N/A

N/A

### Introduction to geospatial analysis with R

Invited teacher in Ecology, Biodiversity and Evolution Graduate Program
<br>
São Paulo State University (UNESP)

Rio Claro, SP, Brazil

2020

::: concise
- 60 h 
:::

### Statistical Models in Ecology

Teacher in Ecology Undergraduate
<br>
São Paulo State University (UNESP)

Rio Claro, SP, Brazil

2020

::: concise
- 30 h 
:::

### Introduction to Geoprocessing for Ethnobiology and Biodiversity Conservation

Invited external teacher in Ethnobiology and Nature Conservation Graduate Program
<br>
Rural Federal University of Pernambuco (UFRPE)

Recife, PE, Brazil

2019

::: concise
- 45 h 
:::

### Statistical Models in Ecology

Teaching assistant in Ecology Undergraduate
<br>
São Paulo State University (UNESP)

Rio Claro, SP, Brazil

2018

::: concise
- 12 h 
:::

### Ecological Niche Modeling: theory and practice

Teaching assistant in Ecology and Biodiversity Graduate Program
<br>
São Paulo State University (UNESP)

Rio Claro, SP, Brazil

2017

::: concise
- 60 h 
:::

### Ecological Niche Modeling: theory and practice

Teaching assistant in Ecology Graduate Program
<br>
The University of Campinas (UNICAMP)

Campinas, SP, Brazil

2016

::: concise
- 45 h 
:::

### Ecological Niche Modeling in R

Teaching assistant in Ecology and Biodiversity Graduate Program
<br>
São Paulo State University (UNESP)

Rio Claro, SP, Brazil

2016

::: concise
- 30 h 
:::

### Quantitative Ecology

Teaching assistant in Ecology Undergraduate
<br>
São Paulo State University (UNESP)

Rio Claro, SP, Brazil

2015

::: concise
- 60 h 
:::


### <u>Short courses</u>

N/A

N/A

N/A

::: aside
My formation...
:::

### Introduction to R Language

Short course instructor
<br>
[XXX Ecology Studies Week](http://www.rc.unesp.br/see/), São Paulo State University (UNESP)

Rio Claro, SP, Brazil

2019

::: concise
- 08 h 
:::

### Introduction to R Language

Short course instructor
<br>
[30ª Biology Studies Week](https://www.facebook.com/SEBioRC/), São Paulo State University (UNESP)

Rio Claro, SP, Brazil

2019

::: concise
- 08 h 
:::

### Introduction to Species Distribution Modeling using R Language: theory and practice

Short course instructor
<br>
[9º Brazilian Congress of Herpetology](https://9cbh.galoa.com.br/)

Campinas, SP, Brazil

2019

::: concise
- 07 h 
:::

### Field work with amphibians

Short course instructor
<br>
[29ª Biology Studies Week](https://www.facebook.com/SEBioRC/), São Paulo State University (UNESP)

Rio Claro, SP, Brazil

2018

::: concise
- 08 h 
:::

### Field herpetology

Short course instructor
<br>
[XXVII Ecology Studies Week](http://www.rc.unesp.br/see/), São Paulo State University (UNESP)

Rio Claro, SP, Brazil

2016

::: concise
- 15 h 
:::

### Introduction to software R: data management, graphs and statistical analysis

Short course instructor
<br>
[XXVII Ecology Studies Week](http://www.rc.unesp.br/see/), São Paulo State University (UNESP)

Rio Claro, SP, Brazil

2016

::: concise
- 16 h 
:::

### Introduction to software R

Short course instructor
<br>
[XXVI Ecology Studies Week](http://www.rc.unesp.br/see/), São Paulo State University (UNESP)

Rio Claro, SP, Brazil

2015

::: concise
- 08 h 
:::

### Organization of data in electronic sheets - Calc

Short course instructor
<br>
[XXV Ecology Studies Week](http://www.rc.unesp.br/see/), São Paulo State University (UNESP)

Rio Claro, SP, Brazil

2014

::: concise
- 08 h 
:::

Publications {data-icon=file}
--------------------------------------------------------------------------------

::: aside
My formation...
:::

### 13. Host diversity outperforms climate as a global driver of symbiont diversity in the bird‐feather mite system

*Diversity and Distributions*

N/A

2020

DOI: [10.1111/ddi.13201](https://doi.org/10.1111/ddi.13201)
<br>
Gusmão RAF, Hernandes FRA, <u>**Vancine MH**</u>, Naka LN, Doña J, Gonçalves-Souza T

### 12. Environmental niche and functional role similarity between invasive and native palms in the Atlantic Forest

*Biological Invasions*

N/A

2020

DOI: [10.1007/s10530-020-02400-8](https://doi.org/10.1007/s10530-020-02400-8)
<br>
Bello C, Cintra ALP, Barreto E, <u>**Vancine MH**</u>, Sobral-Souza T, Graham CH, Galetti M

### 11. Effects of landscape modification on species richness patterns of fruit-feeding butterflies in Brazilian Atlantic Forest

*Diversity and Distributions* 26(2):196-208

N/A

2020

DOI: [10.1111/ddi.13007](https://doi.org/10.1111/ddi.13007)
<br>
Santos JP, Sobral-Souza T, Brown Jr KS, <u>**Vancine MH**</u>, Ribeiro MC, Freitas AVL

### 10. Fragmented tropical forests lose mutualistic plant-animal interactions

*Diversity and Distributions* 26(2):154-168

N/A

2020

DOI: [10.1111/ddi.13010](https://doi.org/10.1111/ddi.13010)
<br>
Marjakangas E, Abrego N, Grøtan V, Lima RAF, Bello C, Bovendorp RS, Culot L, Hasui E, Muylaert RL, Lima F, Niebuhr B, Oliveira AA, Pereira L, Prado I, Stevens RD, <u>**Vancine MH**</u>, Ribeiro MC, Galetti M, Ovaskainen O

### 9. Predicting the potential hybridization zones between native and invasive marmosets within Neotropical biodiversity hotspots

*Global Ecology and Conservation* 20:e00706

N/A

2019

DOI: [10.1016/j.gecco.2019.e00706](https://doi.org/10.1016/j.gecco.2019.e00706)
<br>
Moraes AM, <u>**Vancine MH**</u>, Moraes AM, Cordeiro CLO, Pinto MP, Lima AA, Culot L, Silva TSF, Collevatti RG, Ribeiro MC, Sobral-Souza T

### 8. Land-use changes and the expansion of biofuel crops threaten the giant anteater in southeastern Brazil

*Journal of Mammalogy* 100(2):435–444

N/A

2019

DOI: [10.1093/jmammal/gyz042](https://doi.org/10.1093/jmammal/gyz042)
<br>
Bertassoni A, Costa RT, Gouvea JA, Bianchi BC, Ribeiro JW, <u>**Vancine MH**</u>, Ribeiro MC

### 7. Spatial prediction of risk areas for vector transmission of Trypanosoma cruzi in the State of Paraná, southern Brazil

*PLOS Neglected Tropical Diseases* 12(10):e0006907

N/A

2018

DOI: [10.1371/journal.pntd.0006907](https://doi.org/10.1371/journal.pntd.0006907)
<br>
Ferro e Silva AM, Sobral-Souza T, <u>**Vancine MH**</u>, Muylaert RL, Abreu AP, Pelloso SM, Carvalho MDB, Andrade L, Ribeiro MC, Toledo MJO 

### 6. A note on the territorial limits of the Atlantic Forest

*Oecologia Australis* 22(3):302–311

N/A

2018

DOI: [10.4257/oeco.2018.2203.09](https://doi.org/10.4257/oeco.2018.2203.09)
<br>
Muylaert RL, <u>**Vancine MH**</u>, Bernardo R, Oshima JEF, Sobral-Souza T, Tonett VR, Niebuhr BBS, Ribeiro MC

### 5. ATLANTIC AMPHIBIANS: a data set of amphibian communities from the Atlantic Forests of South America

*Ecology* 99(7):1692–1692

N/A

2018

DOI: [10.1002/ecy.2392](https://doi.org/10.1002/ecy.2392)
<br>
<u>**Vancine MH**</u>, Duarte KS, Souza YS, Giovanelli JGR, Sobrinho PMM, López A, Bovo RP, Maffei F, Lion MB, Ribeiro-Júnior JW, Brassaloti R, Ortiz C, Sawakuchi HO, Forti LR, Cacciali P, Bertoluci J, Haddad CFB, Ribeiro MC

### 4. Efficiency of protected areas in Amazon and Atlantic Forest conservation: A spatio-temporal view

*Acta Oecologica* 87:1–7

N/A

2018

DOI: [10.1016/j.actao.2018.01.001](https://doi.org/10.1016/j.actao.2018.01.001)
<br>
Sobral-Souza T, <u>**Vancine MH**</u>, Ribeiro MC, Lima-Ribeiro MS

### 3. Forest cover influences occurrence of mammalian carnivores within Brazilian Atlantic Forest

*Journal of Mammalogy* 98:1721–1731

N/A

2017

DOI: [10.1093/jmammal/gyx103](https://doi.org/10.1093/jmammal/gyx103)
<br>
Regolin AL, Cherem JJ, Graipel ME, Bogoni JA, Ribeiro JW, <u>**Vancine MH**</u>, Tortato MA, Oliveira-Santos LG, Fantacini FM, Luiz MR, Castilho PV, Ribeiro MC, Cáceres, NC

### 2. Impacts of mining activities on the potential geographic distribution of eastern Brazil mountaintop endemic species. 

*Perspectives in Ecology and Conservation* 15(3):172–178

N/A

2017

DOI: [10.1016/j.pecon.2017.07.005](https://doi.org/10.1016/j.pecon.2017.07.005)
<br>
De Castro Pena J, Goulart F, Fernandes GW, Hoffmann D, Leite FSF, Santos NB, Soares-Filho B, Sobral-Souza T, <u>**Vancine MH**</u>, Rodrigues M

### 1. High mammal species turnover in forest patches immersed in biofuel plantations

*Biological Conservation* 210:352–359

N/A

2017

DOI: [10.1016/j.biocon.2017.02.033](https://doi.org/10.1016/j.biocon.2017.02.033)
<br>
Beca G, <u>**Vancine MH**</u>, Carvalho CS, Pedrosa F, Alves RSC, Buscariol D, Peres CA, Ribeiro MC, Galetti M